# Run Travis CI for R via Docker
#
# Made by Dirk Eddelbuettel in December 2018 and released under GPL (>=2)

os: linux
dist: trusty
sudo: required
services: docker

# with other packages we often say '--no-build-vignettes --no-manual' here
# but this container is set up just for vignette, markdown and latex
# so R_BL_CHK_OPTS is empty here
env:
  global:
    - DOCKER_OPTS="--rm -ti -v $(pwd):/mnt -w /mnt"
      DOCKER_CNTR="rocker/r-rmd"
      R_BLD_CHK_OPTS=""

before_install:
 - docker pull ${DOCKER_CNTR}
 - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} r -p -e 'sessionInfo()'

install:
 - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} R CMD build ${R_BLD_CHK_OPTS} .

script:
 - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} R CMD check ${R_BLD_CHK_OPTS} linl*.tar.gz

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

    
